version: '3.2'

services:

  mysql: # mariadb container
    container_name: development-mariadb
    image: mariadb:10.5
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  pma: # phpMyAdmin container
    container_name: development-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - 8080:80
    links:
      - mysql:db

# 村井さんの環境
# version: '3.2'
#
# services:
#   db:
#     image: mariadb
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MARIADB_ROOT_PASSWORD: example
#       MARIADB_DATABASE: app
#
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - "8080:8080"
